### ISSUE TITLE
GPU voltage control

### ISSUE THREAD

**Issue by yEsPaP** [TALUAtGitHub/android_kernel_samsung_exynos7870#2]
I saw the commit https://github.com/TALUAtGitHub/android_kernel_samsung_exynos7870/commit/1f0be2a2032eb256f288c9f496433d4c5d64db34

my question is, does that even work.

you see the driver sets it to 0.9V by default but its never used, because it is overwriten here:
https://github.com/TALUAtGitHub/android_kernel_samsung_exynos7870/blob/lineage-18.1/drivers/soc/samsung/pwrcal/S5E7870/S5E7870-asv.c#L671

so to change voltage of specific GPU freq you could edit the function for example:
```
static int dvfsg3d_get_asv_table(unsigned int *table)
{
	int lv, max_lv;

	max_lv = asv_dvfs_g3d->table->num_of_lv;

	for (lv = 0; lv < max_lv; lv++)
		table[lv] = get_asv_voltage(cal_asv_dvfs_g3d, lv);

	// ASV table (it can be 0-15, can be diferent on any device, even same model, each needs different voltage for freq)
        // table[0] = idx0 = 1300MHz, so table[1] would be 1246MHz
        // overwrite 1300MHz to 1.1V
	table[0] = 1100000;

	return max_lv;
}

```

then it would work.

**Comment by TALUAtGitHub** [comment]
While the voltage for 1246MHz (we don't have it set to allow up to 1300MHz) is 0.9V by default, it can be set manually to a higher value using the GPU voltage control sysfs interface. Moreover, the GPU frequency also has to be set manually to 1246MHz.

I will never apply any overclock, undervolt, or overvolt to anything by default for concerns of stability, overheating, and increased degradation of any hardware over time (although this might not be too big of a concern since the damage over time may not be very significant, but there certainly would be some amount of additional degradation), with the only exception being a minor overclock to the CPU, which was already applied before I even started to work on this kernel. Any changes to the GPU voltages or frequency should be manually made by someone who has a decent idea of this stuff. That is mostly to say that if a GPU overclock is to be done, the voltages for the relevant frequencies should be set manually to the lowest necessary voltages, instead of having a voltage that is potentially unnecessarily high for some devices that is set by default that would cause more heat and degradation and just any random person overclocking the GPU by simply setting a higher available frequency because "overclock = increase GPU frequency = free extra FPS (and nothing else)". I personally think that on my tablet, I would be able to have 1300MHz with a voltage that is somewhat lower than 1.1V.

Overclocking doesn't seem to work properly, anyway. For some reason, when testing 1246MHz on my Galaxy Tab A, I found that under graphically-intensive tasks, the GPU frequency would only go up to 1246MHz for a few seconds from time to time and go down to 1001MHz for most of the time. I applied the changes in that commit simply for a GPU voltage control interface so that I can undervolt my tablet's GPU - The rest is there mostly because "why not".

With all of this, I don't see any real issues with regards to voltages here.

**Comment by yEsPaP** [comment]
> While the voltage for 1246MHz (we don't have it set to allow up to 1300MHz) is 0.9V by default, it can be set manually to a higher value using the GPU voltage control sysfs interface. Moreover, the GPU frequency also has to be set manually to 1246MHz. It's still set to 1001MHz by default as it is stock.
> 
> I will never apply any overclock, undervolt, or overvolt to anything by default for concerns of stability, overheating, and increased degradation of any hardware over time (although this might not be too big of a concern since the damage over time may not be very significant, but there certainly would be some amount of additional degradation), with the only exception being a minor overclock to the CPU, which was already applied before I even started to work on this kernel. Any changes to the GPU voltages or frequency should be manually made by someone who has a decent idea of this stuff. That is mostly to say that if a GPU overclock is to be done, the voltages for the relevant frequencies should be set manually to the lowest necessary voltages, instead of having a voltage that is potentially unnecessarily high for some devices that is set by default that would cause more heat and degradation and just any random person overclocking the GPU by simply setting a higher available frequency because "overclock = increase GPU frequency = free extra FPS (and nothing else)". I personally think that on my tablet, I would be able to have 1300MHz with a voltage that is somewhat lower than 1.1V.
> 
> Overclocking doesn't seem to work properly, anyway. For some reason, when testing 1246MHz on my Galaxy Tab A, I found that under graphically-intensive tasks, the GPU frequency would only go up to 1246MHz for a few seconds from time to time and go down to 1001MHz for most of the time. I applied the changes in that commit simply for a GPU voltage control interface so that I can undervolt my tablet's GPU - The rest is there mostly because "why not".
> 
> With all of this, I don't see any real issues with regards to voltages here.

interesting because for me the gpu voltage control commit didn't work.

about the 1246 for a few seconds only thing, i've seen the ECT parser lock stuff over 1146MHz

https://github.com/TALUAtGitHub/android_kernel_samsung_exynos7870/blob/lineage-18.1/drivers/soc/samsung/ect_parser.c

You can check, edit the values of some stuff before returning (i forgot which function it was) but probably `struct ect_dvfs_domain *ect_dvfs_get_domain(void *block, char *domain_name)`

and inside the
```
	for (i = 0; i < header->num_of_domain; ++i) {
		domain = &header->domain_list[i];
```

you could put this

```
			// g3d
			if (domain->domain_offset == 2288) {
				// Enable frequencies up to 1300MHz
				domain->max_frequency = 1300000;
				domain->list_level[0].level_en = 1;
				domain->list_level[1].level_en = 1;
				domain->list_level[2].level_en = 1;
			}
```

which may unlock the frequencies.

also the amount of voltage for freq you need is based on your CPU asv bin.

the default voltages for 1146MHz 0.86875V ASV15 bin (the best quality chip)
but ASV0 bin needs 1.11875V (worst quality)

again all of this is parsed by ECT.

**Comment by TALUAtGitHub** [comment]
> interesting because for me the gpu voltage control commit didn't work.
Hmm, interesting indeed. I've just made this commit: https://github.com/TALUAtGitHub/android_kernel_samsung_exynos7870/commit/8843ff37249a8e221fde7761157bf6ab4ef432d7 It might work fine with it. All of the voltages I have set are divisible by 6250uV, and the voltage that's too low I set for testing for 1001MHz, 600000uV, is divisible by 6250uV, so that's probably why it looked like it worked fine.
 
> about the 1246 for a few seconds only thing, i've seen the ECT parser lock stuff over 1146MHz
> https://github.com/TALUAtGitHub/android_kernel_samsung_exynos7870/blob/lineage-18.1/drivers/soc/samsung/ect_parser.c
> 
> You can check, edit the values of some stuff before returning (i forgot which function it was) but probably `struct ect_dvfs_domain *ect_dvfs_get_domain(void *block, char *domain_name)`
> 
> and inside the
> 
> ```
> 	for (i = 0; i < header->num_of_domain; ++i) {
> 		domain = &header->domain_list[i];
> ```
> 
> you could put this
> 
> ```
> 			// g3d
> 			if (domain->domain_offset == 2288) {
> 				// Enable frequencies up to 1300MHz
> 				domain->max_frequency = 1300000;
> 				domain->list_level[0].level_en = 1;
> 				domain->list_level[1].level_en = 1;
> 				domain->list_level[2].level_en = 1;
> 			}
> ```
> 
> which may unlock the frequencies.
> 
> also the amount of voltage for freq you need is based on your CPU asv bin.
> 
> the default voltages for 1146MHz 0.86875V ASV15 bin (the best quality chip)
> but ASV0 bin needs 1.11875V (worst quality)
> 
> again all of this is parsed by ECT.
I see.... Thanks for all of this information. With it, I'll take a look back at this stuff later.
